name: Simple Workflow

on:
  push:
    branches:
      - main  # Change this if your default branch is different
  pull_request:
    branches:
      - main  # Change this if your default branch is different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run a one-line script
      run: echo "Hello, World! This is a simple GitHub Actions workflow."
